version: '3'
dotenv: ['./config/local.yaml']

tasks:
  proto:all:
    cmds:
      - powershell.exe -File ./generate_protos.ps1
    silent: true
  proto:product:
    cmds:
      - protoc -I proto/product proto/product/*.proto --go_out=./gen/go/product --go_opt=paths=source_relative --go-grpc_out=./gen/go/product --go-grpc_opt=paths=source_relative
    silent: true
